/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TodoCheckedEvent, } from "./components/todo-item/todo-item";
export namespace Components {
    interface TodoContainer {
    }
    interface TodoItem {
        "checked": boolean;
        "text": string;
    }
}
declare global {
    interface HTMLTodoContainerElement extends Components.TodoContainer, HTMLStencilElement {
    }
    var HTMLTodoContainerElement: {
        prototype: HTMLTodoContainerElement;
        new (): HTMLTodoContainerElement;
    };
    interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {
    }
    var HTMLTodoItemElement: {
        prototype: HTMLTodoItemElement;
        new (): HTMLTodoItemElement;
    };
    interface HTMLElementTagNameMap {
        "todo-container": HTMLTodoContainerElement;
        "todo-item": HTMLTodoItemElement;
    }
}
declare namespace LocalJSX {
    interface TodoContainer {
    }
    interface TodoItem {
        "checked"?: boolean;
        "onTodoChecked"?: (event: CustomEvent<TodoCheckedEvent>) => void;
        "text"?: string;
    }
    interface IntrinsicElements {
        "todo-container": TodoContainer;
        "todo-item": TodoItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "todo-container": LocalJSX.TodoContainer & JSXBase.HTMLAttributes<HTMLTodoContainerElement>;
            "todo-item": LocalJSX.TodoItem & JSXBase.HTMLAttributes<HTMLTodoItemElement>;
        }
    }
}
